// <auto-generated />
using System;
using AirTicketSalesManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirTicketSalesManagement.Migrations
{
    [DbContext(typeof(AirTicketDbContext))]
    partial class AirTicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirTicketSalesManagement.Models.Chuyenbay", b =>
                {
                    b.Property<string>("SoHieuCb")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SoHieuCB");

                    b.Property<string>("HangHangKhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sbden")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("SBDen")
                        .IsFixedLength();

                    b.Property<string>("Sbdi")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("SBDi")
                        .IsFixedLength();

                    b.Property<double?>("SoGioBay")
                        .HasColumnType("float");

                    b.Property<string>("TtkhaiThac")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TTKhaiThac");

                    b.HasKey("SoHieuCb")
                        .HasName("PK__CHUYENBA__FB4E27FB61189837");

                    b.HasIndex("Sbden");

                    b.HasIndex("Sbdi");

                    b.ToTable("CHUYENBAY", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Ctdv", b =>
                {
                    b.Property<int>("MaCtdv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTDV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtdv"));

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<decimal?>("GiaVeTt")
                        .HasColumnType("money")
                        .HasColumnName("GiaVeTT");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTenHk")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("HoTenHK");

                    b.Property<string>("HoTenNguoiGiamHo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("MaDv")
                        .HasColumnType("int")
                        .HasColumnName("MaDV");

                    b.Property<int?>("MaHvLb")
                        .HasColumnType("int")
                        .HasColumnName("MaHV_LB");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.HasKey("MaCtdv")
                        .HasName("PK__CTDV__1E4E40E6AB632E09");

                    b.HasIndex("MaDv");

                    b.HasIndex("MaHvLb");

                    b.ToTable("CTDV", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Datve", b =>
                {
                    b.Property<int>("MaDv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDv"));

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)");

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaLb")
                        .HasColumnType("int")
                        .HasColumnName("MaLB");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<int?>("Slve")
                        .HasColumnType("int")
                        .HasColumnName("SLVe");

                    b.Property<string>("SoDtlienLac")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("SoDTLienLac")
                        .IsFixedLength();

                    b.Property<DateTime?>("ThoiGianDv")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianDV");

                    b.Property<decimal?>("TongTienTt")
                        .HasColumnType("money")
                        .HasColumnName("TongTienTT");

                    b.Property<string>("TtdatVe")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TTDatVe");

                    b.HasKey("MaDv")
                        .HasName("PK__DATVE__27258657DB4E68B5");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaLb");

                    b.HasIndex("MaNv");

                    b.ToTable("DATVE", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Hangve", b =>
                {
                    b.Property<int>("MaHv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHv"));

                    b.Property<double?>("HeSoGia")
                        .HasColumnType("float");

                    b.Property<string>("TenHv")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenHV");

                    b.HasKey("MaHv")
                        .HasName("PK__HANGVE__2725A6D21B1F6F99");

                    b.ToTable("HANGVE", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Hangvetheolichbay", b =>
                {
                    b.Property<int>("MaHvLb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHV_LB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHvLb"));

                    b.Property<int?>("MaHv")
                        .HasColumnType("int")
                        .HasColumnName("MaHV");

                    b.Property<int?>("MaLb")
                        .HasColumnType("int")
                        .HasColumnName("MaLB");

                    b.Property<int?>("SlveConLai")
                        .HasColumnType("int")
                        .HasColumnName("SLVeConLai");

                    b.Property<int?>("SlveToiDa")
                        .HasColumnType("int")
                        .HasColumnName("SLVeToiDa");

                    b.HasKey("MaHvLb")
                        .HasName("PK__HANGVETH__1853D482890994ED");

                    b.HasIndex("MaHv");

                    b.HasIndex("MaLb");

                    b.ToTable("HANGVETHEOLICHBAY", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Khachhang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTenKh")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("HoTenKH");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("SoDT")
                        .IsFixedLength();

                    b.HasKey("MaKh")
                        .HasName("PK__KHACHHAN__2725CF1E96A6589D");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Lichbay", b =>
                {
                    b.Property<int>("MaLb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLb"));

                    b.Property<decimal?>("GiaVe")
                        .HasColumnType("money");

                    b.Property<DateTime?>("GioDen")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("GioDi")
                        .HasColumnType("datetime");

                    b.Property<string>("LoaiMb")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("LoaiMB");

                    b.Property<int?>("SlveKt")
                        .HasColumnType("int")
                        .HasColumnName("SLVeKT");

                    b.Property<string>("SoHieuCb")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SoHieuCB");

                    b.Property<string>("TtlichBay")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TTLichBay");

                    b.HasKey("MaLb")
                        .HasName("PK__LICHBAY__2725C761440C3794");

                    b.HasIndex("SoHieuCb");

                    b.ToTable("LICHBAY", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Nhanvien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTenNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HoTenNV");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("SoDT")
                        .IsFixedLength();

                    b.HasKey("MaNv")
                        .HasName("PK__NHANVIEN__2725D70A8A5D21A0");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Quydinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SoHangVe")
                        .HasColumnType("int");

                    b.Property<int?>("SoSanBay")
                        .HasColumnType("int");

                    b.Property<int?>("SoSanBayTgtoiDa")
                        .HasColumnType("int")
                        .HasColumnName("SoSanBayTGToiDa");

                    b.Property<int?>("TgdatVeChamNhat")
                        .HasColumnType("int")
                        .HasColumnName("TGDatVeChamNhat");

                    b.Property<int?>("TgdungMax")
                        .HasColumnType("int")
                        .HasColumnName("TGDungMax");

                    b.Property<int?>("TgdungMin")
                        .HasColumnType("int")
                        .HasColumnName("TGDungMin");

                    b.Property<int?>("TghuyDatVe")
                        .HasColumnType("int")
                        .HasColumnName("TGHuyDatVe");

                    b.Property<int?>("ThoiGianBayToiThieu")
                        .HasColumnType("int");

                    b.Property<int?>("TuoiToiDaSoSinh")
                        .HasColumnType("int")
                        .HasColumnName("TuoiToiDaSoSinh");

                    b.Property<int?>("TuoiToiDaTreEm")
                        .HasColumnType("int")
                        .HasColumnName("TuoiToiDaTreEm");

                    b.HasKey("Id")
                        .HasName("PK__QUYDINH__3214EC27DB96B719");

                    b.ToTable("QUYDINH", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Sanbay", b =>
                {
                    b.Property<string>("MaSb")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("MaSB")
                        .IsFixedLength();

                    b.Property<string>("QuocGia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenSb")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenSB");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaSb")
                        .HasName("PK__SANBAY__2725080E986CBE4F");

                    b.ToTable("SANBAY", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Sanbaytrunggian", b =>
                {
                    b.Property<int>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("STT");

                    b.Property<string>("SoHieuCb")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SoHieuCB");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaSbtg")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("MaSBTG")
                        .IsFixedLength();

                    b.Property<int?>("ThoiGianDung")
                        .HasColumnType("int");

                    b.HasKey("Stt", "SoHieuCb")
                        .HasName("PK__SANBAYTR__65AA54EFED1205D1");

                    b.HasIndex("MaSbtg");

                    b.HasIndex("SoHieuCb");

                    b.ToTable("SANBAYTRUNGGIAN", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Taikhoan", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTk"));

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)");

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaNv")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTk")
                        .HasName("PK__TAIKHOAN__27250070FBD01FEA");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.HasIndex(new[] { "Email" }, "UQ__TAIKHOAN__A9D10534CAAAFF1D")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Chuyenbay", b =>
                {
                    b.HasOne("AirTicketSalesManagement.Models.Sanbay", "SbdenNavigation")
                        .WithMany("ChuyenbaySbdenNavigations")
                        .HasForeignKey("Sbden")
                        .HasConstraintName("FK__CHUYENBAY__SBDen__3A81B327");

                    b.HasOne("AirTicketSalesManagement.Models.Sanbay", "SbdiNavigation")
                        .WithMany("ChuyenbaySbdiNavigations")
                        .HasForeignKey("Sbdi")
                        .HasConstraintName("FK__CHUYENBAY__SBDi__398D8EEE");

                    b.Navigation("SbdenNavigation");

                    b.Navigation("SbdiNavigation");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Ctdv", b =>
                {
                    b.HasOne("AirTicketSalesManagement.Models.Datve", "MaDvNavigation")
                        .WithMany("Ctdvs")
                        .HasForeignKey("MaDv")
                        .HasConstraintName("FK__CTDV__MaDV__52593CB8");

                    b.HasOne("AirTicketSalesManagement.Models.Hangvetheolichbay", "MaHvLbNavigation")
                        .WithMany("Ctdvs")
                        .HasForeignKey("MaHvLb")
                        .HasConstraintName("FK__CTDV__MaHV_LB__534D60F1");

                    b.Navigation("MaDvNavigation");

                    b.Navigation("MaHvLbNavigation");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Datve", b =>
                {
                    b.HasOne("AirTicketSalesManagement.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Datves")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__DATVE__MaKH__4E88ABD4");

                    b.HasOne("AirTicketSalesManagement.Models.Lichbay", "MaLbNavigation")
                        .WithMany("Datves")
                        .HasForeignKey("MaLb")
                        .HasConstraintName("FK__DATVE__MaLB__4D94879B");

                    b.HasOne("AirTicketSalesManagement.Models.Nhanvien", "MaNvNavigation")
                        .WithMany("Datves")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__DATVE__MaNV__4F7CD00D");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaLbNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Hangvetheolichbay", b =>
                {
                    b.HasOne("AirTicketSalesManagement.Models.Hangve", "MaHvNavigation")
                        .WithMany("Hangvetheolichbays")
                        .HasForeignKey("MaHv")
                        .HasConstraintName("FK__HANGVETHEO__MaHV__46E78A0C");

                    b.HasOne("AirTicketSalesManagement.Models.Lichbay", "MaLbNavigation")
                        .WithMany("Hangvetheolichbays")
                        .HasForeignKey("MaLb")
                        .HasConstraintName("FK__HANGVETHEO__MaLB__45F365D3");

                    b.Navigation("MaHvNavigation");

                    b.Navigation("MaLbNavigation");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Lichbay", b =>
                {
                    b.HasOne("AirTicketSalesManagement.Models.Chuyenbay", "SoHieuCbNavigation")
                        .WithMany("Lichbays")
                        .HasForeignKey("SoHieuCb")
                        .HasConstraintName("FK__LICHBAY__SoHieuC__412EB0B6");

                    b.Navigation("SoHieuCbNavigation");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Sanbaytrunggian", b =>
                {
                    b.HasOne("AirTicketSalesManagement.Models.Sanbay", "MaSbtgNavigation")
                        .WithMany("Sanbaytrunggians")
                        .HasForeignKey("MaSbtg")
                        .HasConstraintName("FK__SANBAYTRU__MaSBT__3D5E1FD2");

                    b.HasOne("AirTicketSalesManagement.Models.Chuyenbay", "SoHieuCbNavigation")
                        .WithMany("Sanbaytrunggians")
                        .HasForeignKey("SoHieuCb")
                        .IsRequired()
                        .HasConstraintName("FK__SANBAYTRU__SoHie__3E52440B");

                    b.Navigation("MaSbtgNavigation");

                    b.Navigation("SoHieuCbNavigation");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Taikhoan", b =>
                {
                    b.HasOne("AirTicketSalesManagement.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Taikhoans")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__TAIKHOAN__MaKH__5AEE82B9");

                    b.HasOne("AirTicketSalesManagement.Models.Nhanvien", "MaNvNavigation")
                        .WithMany("Taikhoans")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__TAIKHOAN__MaNV__59FA5E80");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Chuyenbay", b =>
                {
                    b.Navigation("Lichbays");

                    b.Navigation("Sanbaytrunggians");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Datve", b =>
                {
                    b.Navigation("Ctdvs");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Hangve", b =>
                {
                    b.Navigation("Hangvetheolichbays");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Hangvetheolichbay", b =>
                {
                    b.Navigation("Ctdvs");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Khachhang", b =>
                {
                    b.Navigation("Datves");

                    b.Navigation("Taikhoans");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Lichbay", b =>
                {
                    b.Navigation("Datves");

                    b.Navigation("Hangvetheolichbays");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Nhanvien", b =>
                {
                    b.Navigation("Datves");

                    b.Navigation("Taikhoans");
                });

            modelBuilder.Entity("AirTicketSalesManagement.Models.Sanbay", b =>
                {
                    b.Navigation("ChuyenbaySbdenNavigations");

                    b.Navigation("ChuyenbaySbdiNavigations");

                    b.Navigation("Sanbaytrunggians");
                });
#pragma warning restore 612, 618
        }
    }
}
